# -*- coding: utf-8 -*-
"""E-Commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aa90prPAn1eI90BiunACy6pjPjE-BRo5
"""

import pandas as pd

# Esto configura el formato para todo el cuaderno:
# {:,.2f}: separador de miles, dos decimales.
pd.options.display.float_format = '{:,.2f}'.format

# 1. Definimos los nombres manualmente (en el orden exacto de tu Vista de SQL)
nombres_columnas = [
    'InvoiceNo', 'StockCode', 'Description', 'Quantity',
    'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country',
    'Total_Bruto', 'Tasa_Conversion'
]

# 2. Cargamos el archivo avisando que NO tiene encabezado
df = pd.read_csv('Dataset_Ecommerce_Limpio.csv', names=nombres_columnas, header=None)

# 3. El Diccionario de Categorías
mapa_categorias = {
    'HEART': 'Decoración Amor',
    'RETROSPOT': 'Línea Retrospot',
    'VINTAGE': 'Estilo Vintage',
    'DESIGN': 'Artículos de Diseño',
    'CHRISTMAS': 'Temporada Navidad',
    'BAG': 'Bolsos y Almacenamiento',
    'LUNCH': 'Artículos de Almuerzo',
    'LIGHT': 'Iluminación',
    'KITCHEN': 'Cocina',
    'CAKE': 'Repostería',
    'PARTY': 'Artículos de Fiesta',
    'TOY': 'Juguetería',
    'POSTAGE': 'Servicios Logísticos'
}

def categorizar(descripcion):
    texto = str(descripcion).upper()
    for palabra, cat in mapa_categorias.items():
        if palabra in texto:
            return cat
    return 'Otros'

# 4. Aplicamos y calculamos
df['Categoria'] = df['Description'].apply(categorizar)
df['Revenue_USD'] = df['Total_Bruto'] * df['Tasa_Conversion']

print("¡Ahora sí! Columnas detectadas:", df.columns.tolist())
print("\nResumen de Ventas por Categoría (USD):")
print(df.groupby('Categoria')['Revenue_USD'].sum().sort_values(ascending=False))

print(df['Revenue_USD'].sum())

# Guardamos el resultado final en un CSV limpio
# index=False es para que no agregar una columna de números extra
df.to_csv('Ecommerce_Data_Final_Para_PBI.csv', index=False)

print("¡Archivo listo para descargar!")